### ISSUE TITLE
Unable to run since the apk path and devicelist is null

### ISSUE THREAD

**Issue by pmthuan102** [saint228/DreamMultiDevices#11]
Hi,
Sorry for using English because I don't know much as Chinese, I'm really interesting about your framework, it would be a big help for me when performing the automation testing.

But I'm got a trouble with the config.ini file, so could you please help me to clarify some point as below:

1 - Does it should work when we using ADB via USB? 
2 - If the application already installed in device, do we need the APK path? 

I really appreciate your help and really exciting your framework.

Thanks a lot.

**Comment by saint228** [comment]
answer1：Framework use the ADB in Airtest by default。
e.g.:  \Python3.7\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe

In MultiAdb.py,i use the code
```
from airtest.core.android.adb import ADB
adb = ADB().adb_path
```
to import ADB from airtest
if your adb work uncorrectly,make sure your adb version is 40,as airtest's adb version is 40.

answer2：set the "skip_check_of_install" to 0 from config.ini to skip autoinstall. 
and delete the code 
```
if Madb().get_apkpath()=="" or Madb().get_packagename()=="":
        print("配置文件填写不全，packagename和apkpath是必填项")
        devicesList=None
```
from index.py
then you can ignore the  apkpath

**Comment by pmthuan102** [comment]
Hi @saint228 , for the #2, I thought we need to set the "skip_check_of_install" values from 0 to 1 to enable skip apk installation. 
I saw from your comment about that with 0 = False and 1 = True

btw, it keeping error when start the start.py file

I'm using Macbook to run this framework, is it possible to run it with MacOS? 

`Traceback (most recent call last):
  File "/Users/pmthuan/Documents/WearOS_Automate/pytest/start.py", line 15, in <module>
    start()
  File "/Users/pmthuan/Documents/WearOS_Automate/pytest/start.py", line 9, in start
    index.main()
  File "/Users/pmthuan/Documents/WearOS_Automate/pytest/core/index.py", line 31, in main
    devicesList = Madb().get_devicesList()
  File "/Users/pmthuan/Documents/WearOS_Automate/pytest/core/MultiAdb.py", line 43, in __init__
    self._devicesList = Config.getValue(self._configPath, "deviceslist", )
  File "/Users/pmthuan/Documents/WearOS_Automate/pytest/tools/Config.py", line 10, in getValue
    result = con.get("config",key)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'config'
`

**Comment by saint228** [comment]
> Hi @saint228 , for the #2, I thought we need to set the "skip_check_of_install" values from 0 to 1 to enable skip apk installation.
> I saw from your comment about that with 0 = False and 1 = True
> 
> btw, it keeping error when start the start.py file
> 
> I'm using Macbook to run this framework, is it possible to run it with MacOS?
> 
> `Traceback (most recent call last): File "/Users/pmthuan/Documents/WearOS_Automate/pytest/start.py", line 15, in <module> start() File "/Users/pmthuan/Documents/WearOS_Automate/pytest/start.py", line 9, in start index.main() File "/Users/pmthuan/Documents/WearOS_Automate/pytest/core/index.py", line 31, in main devicesList = Madb().get_devicesList() File "/Users/pmthuan/Documents/WearOS_Automate/pytest/core/MultiAdb.py", line 43, in __init__ self._devicesList = Config.getValue(self._configPath, "deviceslist", ) File "/Users/pmthuan/Documents/WearOS_Automate/pytest/tools/Config.py", line 10, in getValue result = con.get("config",key) File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 780, in get d = self._unify_values(section, vars) File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1146, in _unify_values raise NoSectionError(section) from None configparser.NoSectionError: No section: 'config' `

yes，It is a clerical error,"skip_check_of_install" values should be 1.

The framework was designed for windows.
If you use mac，you need to check every filepath,just like “ getValue result = con.get("config",key)” .This function "getValue()" can get the config file from Windows filesysetem,but not work in Mac filesystem.
Revise the Window-filepath-code to Mac-filepath-code is the work for you to do.
Good luck.

**Comment by pmthuan102** [comment]
Thanks @saint228, I will try to convert this framework to Mac, hopefully this framework included multiple host devices supported in the near future.
