### ISSUE TITLE
pip install 报错了

### ISSUE THREAD

**Issue by bsshanghai** [saint228/DreamMultiDevices#2]
Collecting DreamMultiDevices
  Using cached https://files.pythonhosted.org/packages/d6/65/9e68e933825dba8f0fdaf9284e0ef3f3506c8dff4cff3e0cfdd30dd12084/DreamMultiDevices-1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\pip-install-ornoym\DreamMultiDevices\setup.py", line 8, in <module>
        with open("README.md", "r",encoding='utf-8') as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function

麻烦看下这个encoding 字段 出了啥问题了吗？

**Comment by saint228** [comment]
比较奇怪的问题，我下次更新的时候把readme.md拿掉吧。这个文件是直接用的git生成的md文件。没去关注过encoding的问题。这个文件反正也不影响功能。

**Comment by saint228** [comment]
你可以先用git下载压缩包使用。毕竟pip更新频率比git慢得多。
