### ISSUE TITLE
安卓原生 + WEEX 无法抓取fps数据

### ISSUE THREAD

**Issue by 15910908280** [saint228/DreamMultiDevices#4]
我们安卓APP是用原生+WEEX写的，无法抓取fps数据

**Comment by saint228** [comment]
会尝试通过添加gfxinfo的方式解决

**Comment by saint228** [comment]
28c1dcb8390c52c9ee4c2a27daa029240b565445 尝试解决。

**Comment by saint228** [comment]
看了几天，貌似可以。先close，有问题再开。
