### ISSUE TITLE
生成json文件，会放在根目录，还有Report中的html文件能覆盖嘛？

### ISSUE THREAD

**Issue by dgzGitHub** [saint228/DreamMultiDevices#5]
![image](https://user-images.githubusercontent.com/32659576/63738348-08e2d100-c8bc-11e9-9f73-1cf8c9ac37ea.png)
![image](https://user-images.githubusercontent.com/32659576/63738361-1435fc80-c8bc-11e9-8279-4518f214efd6.png)

**Comment by saint228** [comment]
3662fb77de1f5047d3a330dc04e835453c115bb9  中修复了路径，现在在report目录下加了个data目录，临时数据都会丢那里。
html是根据时间生成的，不同的用户可能会有不同的需求，统一覆盖操作不合理。这个不动了。
