### ISSUE TITLE
性能报告是怎么来的

### ISSUE THREAD

**Issue by Cuinnchen** [saint228/DreamMultiDevices#9]

**Comment by Sinxs** [comment]
python安装&nbsp;BeautifulReport


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cuinnchen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 晚上6:16
收件人:&nbsp;"saint228/DreamMultiDevices"<DreamMultiDevices@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[saint228/DreamMultiDevices] 性能报告是怎么来的 (#9)

**Comment by saint228** [comment]
Proformance.py负责处理性能相关业务。在index里分进程进行性能监控。
